config/routes.rb
Rails.application.routes.draw do
  root 'posts#index', as: "home"
  get 'about' => 'pages#about'

  resources :posts do
    resources :comments
    resources :likes
  end
end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

app/models/Post.rb
class Post < ApplicationRecord
  has_many :comments
  has_many :likes
  validates :title, presence: true,
  length: {minimum: 5}
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  validates :username, presence: true,
  length: {minimum: 3}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)
    redirect_to posts_path(@post)
  end
  private def comment_params
    params.require(:comment).permit(:username, :body)
  end
  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to posts_path(@post)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    if(@like = @post.likes.create(like_params))
    redirect_to posts_path(@post)
  else
    render 'home'
  end
  end
  private def like_params
    params.require(:like).permit(:username)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end
  def new
    @post = Post.new
  end

  def show
    @post = Post.find(params[:id])
  end

  def create
    #render plain: params[:post].inspect
    @post = Post.new(post_params)
    if(@post.save)
      redirect_to @post
    else
      render :new
    end
  end
  private def post_params
    params.require(:post).permit(:title, :body)
  end
  def edit
    @post = Post.find(params[:id])
  end
  def update
    @post = Post.find(params[:id])
    if(@post.update(post_params))
      redirect_to @post
    else
      render 'edit'
    end
  end
  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comments.html.erb
<% @post.comments.each do |comment| %>
<div class="well">
  <p><strong> <%= comment.username %></strong>:<%= comment.body %>
    <%= link_to '[x]', [comment.post, comment],
                method: :delete,
                data:{confirm: 'are you sure?'} %></p>
</div>
<% end %>

app/views/comments/_form.html.erb
<h3>Add comment<h3>
  <%= form_for[@post, @post.comments.build] do |form| %>
  <p>
    <%= form.label :username %><br>
    <%= form.text_field(:username, {:class =>'form-control'}) %>
  </p>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area(:body, {:class => 'form-control'}) %>
  </p>
  <p>
    <%= form.submit({:class => 'btn btn-primary'}) %>
  </p>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <title>Simpleapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0" crossorigin="anonymous">
<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-p34f1UUtsS3wqzfto5wAAmdvj+osOnFyQFpp4Ua3gs/ZVWx6oOypYoCJhGGScy+8" crossorigin="anonymous"></script>

  </head>
  <body>
    <nav class="navbar navbar-expand navbar-dark bg-dark" aria-label="Second navbar example">
     <div class="container-fluid">
       <a class="navbar-brand" href="#">Simpleapp</a>
       <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExample02" aria-controls="navbarsExample02" aria-expanded="false" aria-label="Toggle navigation">
         <span class="navbar-toggler-icon"></span>
       </button>
       <div class="collapse navbar-collapse" id="navbarsExample02">
         <ul class="navbar-nav me-auto">
           <li class="nav-item">
             <span class="nav-link"><%= link_to "Home", home_path  %></span>
           </li>
           <li class="nav-item ">
             <span class="nav-link"><%= link_to "About Us", about_path  %></span>
           </li>
           <li class="nav-item bg-light justify-content-end">
             <span class="nav-link"><%= link_to "Create Post", new_post_path %></span>
           </li>
           </ul>
       </div>
     </div>
    </nav>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/likes/_likes.html.erb
<h3>Enter Username<h3>
  <%= form_for [post, post.likes.build] do |form| %>
    <p>
      <%= form.label :username %><br>
      <%= form.text_field(:username, {:class =>'form-control'}) %>
    </p>
    <p>
      <%= form.submit({:class => 'btn btn-primary'}) %>
    </p>
  <% end %>

app/views/pages/about.html.erb
<h1>About Us</h1>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>
<%= form_for :post, url: post_path(@post), method: :patch do |form|%>
<% if @post.errors.any? %>
  <% @post.errors.full_messages.each do |msg| %>
  <div class="alert alert-danger">
    <%= msg %>
  </div>
  <% end %>
<% end %>
<p>
  <%= form.label :title %><br>
  <%= form.text_field(:title, {:class =>'form-control'}) %>
</p>
<p>
  <%= form.label :body %><br>
  <%= form.text_area(:body, {:class => 'form-control'}) %>
</p>
<p>
  <%= form.submit({:class => 'btn btn-primary'}) %>
</p>
<% end %>

app/views/posts/index.html.erb
<h1>POSTS</h1>
<br>
<% @posts.each do |post| %>
<div class="well bg-light">
  <hr>
  <%= link_to "Click here to modify...", post_path(post),  :class => 'btn btn-link' %>
    <h3><%= post.title %> </h3>
    <p><%= post.body %> <p>
      <p> <%= post.likes.count %> likes</p>
      <hr>
      <div class="container-fluid">
  <div class="row">
    <div class="col-sm-3">
      <div class="accordion" id="accordionExample">
        <div class="accordion-item">
          <h2 class="accordion-header" id="headingOne">
            <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
              Like
            </button>
          </h2>
          <div id="collapseOne" class="accordion-collapse collapse show" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
            <div class="accordion-body">
              <p>
              <%= form_for [post, post.likes.build] do |form| %>
                  <%= form.label :username %>
                  <%= form.text_field(:username)%>
                  <%= form.submit("LIKE",{:class => 'btn btn-primary'}) %>
              <% end %>
              </p>
            </div>
          </div>
        </div>
      </div>
      </div>
      <div class="col-sm-4">
        <div class="accordion" id="accordionExample">
          <div class="accordion-item">
            <h2 class="accordion-header" id="headingOne">
              <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                Comments
              </button>
            </h2>
            <div id="collapseOne" class="accordion-collapse collapse show" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
              <div class="accordion-body">
                <% post.comments.each do |comment| %>
                  <div class="well">
                    <p><strong> <%= comment.username %></strong>:<%= comment.body %>
                      <%= link_to '[x]', [comment.post, comment], method: :delete, data:{confirm: 'are you sure?'} %>
                    </p>
                  </div>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-sm-4">
      <div class="accordion" id="accordionExample">
        <div class="accordion-item">
          <h2 class="accordion-header" id="headingOne">
            <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
              ADD Comments
            </button>
          </h2>
          <div id="collapseOne" class="accordion-collapse collapse show" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
            <div class="accordion-body">
              <%= form_for [post, post.comments.build] do |form| %>
                <span>
                  <%= form.label :username %><%= form.text_field(:username) %><br> <br>
                </span>
                <p>
                  <%= form.text_area(:body, {:class => 'form-control', autofocus: true, placeholder: 'type your comment here'}) %>
                </p>
                <p>
                  <%= form.submit("Comment",{:class => 'btn btn-primary'}) %>
                </p>
                <br>
                <hr>
              <% end %>
            </div>
          </div>
        </div>
      </div>
      </div>
      </div>
</div>
<br>
<% end %>

app/views/posts/new.html.erb
<h1>ADD NEW POST</h1>
<%= form_for :post, url: posts_path do |form|%>
<% if @post.errors.any? %>
  <% @post.errors.full_messages.each do |msg| %>
  <div class="alert alert-danger">
    <%= msg %>
  </div>
  <% end %>
<% end %>
<p>
  <%= form.label :title %><br>
  <%= form.text_field(:title, {:class =>'form-control'}) %>
</p>
<p>
  <%= form.label :body %><br>
  <%= form.text_area(:body, {:class => 'form-control'}) %>
</p>
<p>
  <%= form.submit({:class => 'btn btn-primary'}) %>
</p>
<% end %>

app/views/posts/show.html.erb
<h2> <%= @post.title %> </h2>
<p> <%= @post.body %> </p>
<hr>
<%= link_to "Edit", edit_post_path(@post), :class => 'btn btn-warning' %>
<%= link_to "Delete", post_path(@post),
            method: :delete,
            data:{confirm: 'are you sure?'},
:class => 'btn btn-danger' %>
<hr>